quotes = [
    "First forget inspiration. Habit is more dependable. Habit will sustain you whether you're inspired or not. Habit will help you finish and polish your stories. Inspiration won't. Habit is persistence in practice.",
    "Keep your friends rich, but your enemies richer",
    "Life begins at the end your comfort zone",
    "Don't be same, be better!",
    "All our dreams can come true, if we have the courage to pursue them.",
    "success is not final;failure is not fatal; it is the courage to continue that counts",
    "SUCCESS comes to those who ACT",
    "Don't Focus On The Pain, Focus On the Progress",
    "If your dream don't scare you they are too small",
    "Think Big. Trust Yourself And Make It Happen",
    "A negative mind will never give you a positive life",
    "study hard play hard and be smart",
    "focus on the outcome not the obstacle",
    "you need to know what to do when the sun is not shining - RDJ",
    "just because you hit bottom, it doesn't mean that you have to stay there - RDJ",
    "You only fail when you stop trying",
    "good things take time",
    "a smooth sea never made a skilled sailor",
    "the best fighter is never angry",
    "understand the results of your action",
    "train your mind to stay calm in every situation",
    "some enemies look like friends",
    "focus on the goals not the distractions",
    "success is not always what we see",
    "if there is no way create one",
    "happiness comes in wave it will find you again",
    "it nice to be important, but its important to be nice",
    "Everything is gonna workout exactly the way its suppose to",
    "Sometimes you gotta run before you can walk",
    "If there is no enemy within, the enemy outside can do us no harm",
    "Your greatest enemy is you",
]
